export const PRODUCTS = [
  {id:"p1", name:"Aurora Wireless Headphones", category:"Audio", price:129, compareAt:179, rating:4.6, reviews:321, created:"2025-10-03", tags:["wireless","bluetooth","new"], img:"🎧", desc:"Comfort-fit over-ear wireless headphones with 35h battery life, ANC, and low-latency mode."},
  {id:"p2", name:"Nimbus Mechanical Keyboard", category:"Accessories", price:99, compareAt:0, rating:4.4, reviews:210, created:"2025-05-18", tags:["hot-swap","rgb"], img:"⌨️", desc:"Hot‑swappable, gasket‑mounted 75% mechanical keyboard with south-facing RGB."},
  {id:"p3", name:"Pulse Fitness Smartwatch", category:"Wearables", price:159, compareAt:199, rating:4.2, reviews:180, created:"2025-12-12", tags:["health","gps","waterproof"], img:"⌚", desc:"AMOLED display, continuous HRV, SpO₂, GPS, and 7‑day battery."},
  {id:"p4", name:"Lumen 4K Action Camera", category:"Cameras", price:279, compareAt:349, rating:4.5, reviews:92, created:"2025-08-22", tags:["4k","60fps","stabilization"], img:"📷", desc:"Compact 4K/60 action cam with advanced stabilization and horizon lock."},
  {id:"p5", name:"Comet USB‑C GaN Charger 65W", category:"Power", price:39, compareAt:59, rating:4.7, reviews:640, created:"2025-04-01", tags:["gan","usb-c","fast-charge"], img:"🔌", desc:"Dual‑port 65W GaN charger for phones, tablets, and ultrabooks."},
  {id:"p6", name:"Drift Portable Speaker", category:"Audio", price:79, compareAt:99, rating:4.1, reviews:510, created:"2024-11-15", tags:["waterproof","bass"], img:"🔊", desc:"IP67 waterproof portable speaker with punchy bass and 12h playtime."},
  {id:"p7", name:"Orbit Wireless Mouse", category:"Accessories", price:49, compareAt:0, rating:4.0, reviews:870, created:"2024-09-20", tags:["silent-click","bluetooth"], img:"🖱️", desc:"Ergonomic wireless mouse with multi‑device pairing."},
  {id:"p8", name:"Trail Pro Backpack 28L", category:"Outdoors", price:119, compareAt:139, rating:4.8, reviews:154, created:"2025-06-10", tags:["durable","lightweight"], img:"🎒", desc:"Lightweight, weather‑resistant everyday carry backpack."},
  {id:"p9", name:"Zen Studio Lamp", category:"Home", price:69, compareAt:0, rating:4.3, reviews:77, created:"2025-03-03", tags:["dimmable","usb-c"], img:"💡", desc:"Minimalist LED lamp with ambient dimming and USB‑C."},
  {id:"p10", name:"Glide Running Shoes", category:"Apparel", price:139, compareAt:169, rating:4.6, reviews:390, created:"2025-01-12", tags:["breathable","cushion"], img:"👟", desc:"Responsive daily trainers with breathable mesh upper."},
  {id:"p11", name:"Summit Insulated Bottle 1L", category:"Outdoors", price:35, compareAt:0, rating:4.9, reviews:1240, created:"2024-08-02", tags:["bpa-free","hot-cold"], img:"🥤", desc:"Keeps drinks cold 24h / hot 12h. BPA‑free, leakproof."},
  {id:"p12", name:"Arc USB‑C Hub 7‑in‑1", category:"Accessories", price:59, compareAt:79, rating:4.2, reviews:430, created:"2024-12-30", tags:["hdmi","usb-c","sd"], img:"🧩", desc:"7‑port hub with 4K HDMI, SD, and 100W PD pass‑through."}
];